name: macOS tests

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run macOS tests
      run: xcodebuild test -scheme 'macOS' -enableCodeCoverage YES
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'Fragment'
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "iOS tests"
        description: "Run all macOS tests"
        username: Github
        avatar_url: ${{ secrets.AVATAR_URL }}
